# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

try:
    from discord_grpc import discord_webhook_pb2 as discord__webhook__pb2
except ImportError:  # pragma: no cover - fallback for direct script usage
    from . import discord_webhook_pb2 as discord__webhook__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in discord_webhook_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DiscordWebhookStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendText = channel.unary_unary(
                '/discord_webhook.DiscordWebhook/SendText',
                request_serializer=discord__webhook__pb2.SendTextRequest.SerializeToString,
                response_deserializer=discord__webhook__pb2.SendResponse.FromString,
                _registered_method=True)
        self.SendImage = channel.unary_unary(
                '/discord_webhook.DiscordWebhook/SendImage',
                request_serializer=discord__webhook__pb2.SendImageRequest.SerializeToString,
                response_deserializer=discord__webhook__pb2.SendResponse.FromString,
                _registered_method=True)
        self.SendVideo = channel.unary_unary(
                '/discord_webhook.DiscordWebhook/SendVideo',
                request_serializer=discord__webhook__pb2.SendVideoRequest.SerializeToString,
                response_deserializer=discord__webhook__pb2.SendResponse.FromString,
                _registered_method=True)


class DiscordWebhookServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendImage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendVideo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DiscordWebhookServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendText': grpc.unary_unary_rpc_method_handler(
                    servicer.SendText,
                    request_deserializer=discord__webhook__pb2.SendTextRequest.FromString,
                    response_serializer=discord__webhook__pb2.SendResponse.SerializeToString,
            ),
            'SendImage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendImage,
                    request_deserializer=discord__webhook__pb2.SendImageRequest.FromString,
                    response_serializer=discord__webhook__pb2.SendResponse.SerializeToString,
            ),
            'SendVideo': grpc.unary_unary_rpc_method_handler(
                    servicer.SendVideo,
                    request_deserializer=discord__webhook__pb2.SendVideoRequest.FromString,
                    response_serializer=discord__webhook__pb2.SendResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'discord_webhook.DiscordWebhook', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('discord_webhook.DiscordWebhook', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DiscordWebhook(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/discord_webhook.DiscordWebhook/SendText',
            discord__webhook__pb2.SendTextRequest.SerializeToString,
            discord__webhook__pb2.SendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/discord_webhook.DiscordWebhook/SendImage',
            discord__webhook__pb2.SendImageRequest.SerializeToString,
            discord__webhook__pb2.SendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendVideo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/discord_webhook.DiscordWebhook/SendVideo',
            discord__webhook__pb2.SendVideoRequest.SerializeToString,
            discord__webhook__pb2.SendResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
